# Generated by Django 5.1.5 on 2025-01-21 03:06

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique_for_date='publish')),
                ('description', models.TextField()),
                ('article_1', models.TextField()),
                ('article_2', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PU', 'Published')], default='DF', max_length=10)),
                ('admin_status', models.CharField(choices=[('NO', 'None'), ('FG', 'Flagged'), ('AFG', 'Admin Flagged')], default='NO', max_length=10)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_unit', models.CharField(default='amount needed', max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('group_name', models.CharField(default='main', max_length=255)),
                ('group_number', models.IntegerField(default=1, max_length=2)),
                ('admin_status', models.CharField(choices=[('NO', 'None'), ('FG', 'Flagged'), ('AFG', 'Admin Flagged')], default='NO', max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Recipe.recipe')),
            ],
            options={
                'ordering': ['group_number', 'name', '-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('number', models.IntegerField(max_length=2, unique=True)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('admin_status', models.CharField(choices=[('NO', 'None'), ('FG', 'Flagged'), ('AFG', 'Admin Flagged')], default='NO', max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='Recipe.recipe')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Recipe_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin_status', models.CharField(choices=[('NO', 'None'), ('FG', 'Flagged'), ('AFG', 'Admin Flagged')], default='NO', max_length=10)),
                ('Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Recipe.recipe')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-publish', 'title'], name='Recipe_reci_publish_b9b276_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['group_number', 'name', '-date_added'], name='Recipe_ingr_group_n_3b0496_idx'),
        ),
        migrations.AddIndex(
            model_name='directions',
            index=models.Index(fields=['-number'], name='Recipe_dire_number_fd13e6_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe_images',
            index=models.Index(fields=['-created', 'title'], name='Recipe_reci_created_6b941d_idx'),
        ),
    ]
