# Generated by Django 5.1.5 on 2025-01-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='group_name',
            field=models.CharField(default='main', max_length=255),
        ),
        migrations.AddField(
            model_name='directions',
            name='group_number',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
