# Generated by Django 5.1.5 on 2025-01-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0002_directions_group_name_directions_group_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_images',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
