# Generated by Django 5.1.5 on 2025-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_alter_directions_group_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='number',
            field=models.IntegerField(),
        ),
    ]
