# Generated by Django 5.1.5 on 2025-01-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_alter_directions_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='article_1_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='article_2_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
