# Generated by Django 5.1.5 on 2025-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0006_recipe_article_1_title_recipe_article_2_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipe_images',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
